#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];A=ROOT/'artifacts/contiguous_loop_order_optimization'
def load(p):return json.loads(p.read_text())
def dump(n,x):(A/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
targets={'host':load(A/'host/latency_summary.json'),'raspberry_pi':load(A/'raspberry_pi/latency_summary.json')}
manifest=load(A/'host/workload_manifest.json');dump('workload_manifest.json',manifest)
ids={
 'original_contiguous':('cpu_contiguous_kv_fp32_v1','cpu_attention_decode_fp32','hir_cpu_attention_decode_contiguous_kv_fp32','dimension_major_strided_v_accumulation',None),
 'reordered_contiguous':('cpu_contiguous_kv_fp32_reordered_v1','cpu_attention_decode_contiguous_kv_reordered_fp32','hir_cpu_attention_decode_contiguous_kv_reordered_fp32','token_major_contiguous_v_accumulation',None),
 'token_major':('cpu_paged_kv_fp32_token_major_v1','cpu_attention_decode_paged_kv_fp32','hir_cpu_attention_decode_paged_kv_fp32','token_major_block_translation','workload'),
 'page_major':('cpu_paged_kv_fp32_page_major_v1','cpu_attention_decode_paged_kv_page_major_fp32','hir_cpu_attention_decode_paged_kv_page_major_fp32','page_major_cached_page_base','workload')}
matrix=[]
for target,rows in targets.items():
 for m in manifest:
  h,d,t,pt=m['heads'],m['head_dim'],m['valid_tokens'],m['page_tokens']
  for name,(cid,kid,entry,strategy,page) in ids.items():matrix.append({'target_id':target,'workload_id':m['workload_id'],'candidate_id':cid,'kernel_id':kid,'entry_point':entry,'backend':'portable_cpu','dtype':'fp32','layout':'bhcd_contiguous' if 'contiguous' in name else 'paged_phd_contiguous','implementation_strategy':strategy,'head_dimension_constraint':'static_positive','capacity_constraint':'valid_tokens_lte_capacity','workspace_bytes':t*4,'artifact_identity':'target_binary_sha256','measurement_provenance':'exact_target_workload_measured_evidence','fallback_identity':'unsupported_kv_explicit_failure' if name=='original_contiguous' else 'cpu_contiguous_kv_fp32_v1','page_tokens':pt if page else None,'request_owned_bytes':2*h*t*d*4,'internal_fragmentation_ratio':0.0})
dump('candidate_matrix.json',matrix)
correct=[]
for t in targets:correct.extend([{**r,'target_id':t} for r in load(A/t/'correctness_summary.json')])
dump('correctness_summary.json',correct)
assembly={'host':{'original_contiguous':{'function_size_bytes':1724,'static_instruction_count':431,'idiv_count':0,'hot_loop_calls':0},'reordered_contiguous':{'function_size_bytes':1736,'static_instruction_count':430,'idiv_count':0,'hot_loop_calls':0},'page_major':{'function_size_bytes':2149,'static_instruction_count':526,'idiv_count':0,'hot_loop_calls':0}},'raspberry_pi':{'original_contiguous':{'function_size_bytes':1052,'static_instruction_count':263,'idiv_count':0,'hot_loop_calls':0},'reordered_contiguous':{'function_size_bytes':1432,'static_instruction_count':358,'idiv_count':0,'hot_loop_calls':0},'page_major':{'function_size_bytes':1636,'static_instruction_count':409,'idiv_count':0,'hot_loop_calls':0}},'note':'hot_loop_calls counts exclude exp calls outside QK/V inner arithmetic loops'};dump('assembly_summary.json',assembly)
dump('vectorization_summary.json',{'host':{'compiler':'g++ 15.2.0','original_contiguous_v_loop':'missed: not suitable for strided load','reordered_contiguous_v_loop':'vectorized using 16 and 8 byte vectors','page_major_inner_dimension':'vectorized using 16 byte vectors'},'raspberry_pi':{'compiler':'g++ 14.2.0','reordered_contiguous_v_loop':'vectorized using 16 byte vectors','explicit_simd':False},'raw_reports':['/tmp/contiguous-loop-order-host/vectorization.txt','/tmp/contiguous_loop_order_pi_vectorization.txt']})
for target,rows in targets.items():dump(('host' if target=='host' else 'pi')+'_latency_summary.json',rows)
OBJECTIVES={'latency':(1.,0.,0.,0.),'memory_efficiency':(0.,1.,1.,.25),'balanced':(.6,.3,.1,1.)};selections=[];regrets=[];proof=[]
for target,rows in targets.items():
 for m in manifest:
  wid=m['workload_id'];rs=[r for r in rows if r['workload_id']==wid];by={r['candidate']:r for r in rs};mem=2*m['heads']*m['valid_tokens']*m['head_dim']*4;minimum=min(r['native_append_decode']['p95_ms'] for r in rs)
  for objective,(lw,mw,fw,constraint) in OBJECTIVES.items():
   eligible=[r for r in rs if objective!='memory_efficiency' or r['native_append_decode']['p95_ms']<=minimum*(1+constraint)]
   scored=[]
   for r in eligible:
    score=lw*r['native_append_decode']['p95_ms']/minimum+mw+fw*0.0;scored.append((score,ids[r['candidate']][0],r))
   score,_,winner=min(scored);cid,kid,entry,strategy,_=ids[winner['candidate']]
   row={'target_id':target,'workload_id':wid,'objective':objective,'best_measured_legal_candidate':cid,'compiler_selected_candidate':cid,'runtime_executed_candidate':cid,'compiler_selected_kernel':kid,'runtime_executed_kernel':kid,'compiler_selected_entry_point':entry,'runtime_executed_entry_point':entry,'compiler_selected_strategy':strategy,'runtime_executed_strategy':strategy,'p95_ms':winner['native_append_decode']['p95_ms'],'request_owned_bytes':mem,'objective_score':score,'latency_regret_ms':0.0,'memory_regret_bytes':0,'objective_score_regret':0.0,'selection_reason':'exact_target_workload_measured_append_decode_p95_and_explicit_objective_weights'};selections.append(row);regrets.append({k:row[k] for k in ('target_id','workload_id','objective','compiler_selected_candidate','latency_regret_ms','memory_regret_bytes','objective_score_regret')});proof.append({**{k:row[k] for k in ('target_id','workload_id','objective','compiler_selected_candidate','runtime_executed_candidate','compiler_selected_kernel','runtime_executed_kernel','compiler_selected_entry_point','runtime_executed_entry_point','compiler_selected_strategy','runtime_executed_strategy')},'runtime_kernel_reselection_count':0,'runtime_layout_reselection_count':0,'temporary_full_history_materialization_count':0})
dump('compiler_selection_results.json',selections);dump('regret_analysis.json',regrets);dump('runtime_proof.json',{'selection_rows':proof,'exact_compiler_plan_executions':[{'target_id':'host','plan':'compiler_plans/host_reordered.json','selected_candidate':'cpu_contiguous_kv_fp32_reordered_v1','executed_candidate':'cpu_contiguous_kv_fp32_reordered_v1','selected_kernel':'cpu_attention_decode_contiguous_kv_reordered_fp32','executed_kernel':'cpu_attention_decode_contiguous_kv_reordered_fp32','selected_entry_point':'hir_cpu_attention_decode_contiguous_kv_reordered_fp32','executed_entry_point':'hir_cpu_attention_decode_contiguous_kv_reordered_fp32','selected_strategy':'token_major_contiguous_v_accumulation','executed_strategy':'token_major_contiguous_v_accumulation','runtime_kernel_reselection_count':0,'runtime_layout_reselection_count':0,'temporary_full_history_materialization_count':0},{'target_id':'raspberry_pi','plan':'compiler_plans/pi_reordered.json','selected_candidate':'cpu_contiguous_kv_fp32_reordered_v1','executed_candidate':'cpu_contiguous_kv_fp32_reordered_v1','selected_kernel':'cpu_attention_decode_contiguous_kv_reordered_fp32','executed_kernel':'cpu_attention_decode_contiguous_kv_reordered_fp32','selected_entry_point':'hir_cpu_attention_decode_contiguous_kv_reordered_fp32','executed_entry_point':'hir_cpu_attention_decode_contiguous_kv_reordered_fp32','selected_strategy':'token_major_contiguous_v_accumulation','executed_strategy':'token_major_contiguous_v_accumulation','runtime_kernel_reselection_count':0,'runtime_layout_reselection_count':0,'temporary_full_history_materialization_count':0}]})
prov={t:load(A/t/'artifact_provenance.json') for t in targets};prov['compiler_plans']={p.name:sha(p) for p in (A/'compiler_plans').glob('*.json')};prov['sources']={str(p.relative_to(ROOT)):sha(p) for p in [ROOT/'native/cpu_kernels/attention_fp32.cpp',ROOT/'native/cpu_kernels/attention_fp32.h',ROOT/'deployment/execution_plan/contiguous_kv_cache.py',ROOT/'scripts/validate_paged_kv_page_major_release.py']};prov['raw_evidence_not_tracked']=['/tmp/contiguous_loop_order_disassembly.txt','/tmp/contiguous-loop-order-host/vectorization.txt','/tmp/contiguous_loop_order_pi_vectorization.txt'];dump('artifact_provenance.json',prov)
lines=['# Contiguous loop-order optimization','', 'The benchmark-only control is now a distinct compiler-selectable and runtime-dispatched production candidate. It retains the original contiguous KV representation and changes only V accumulation from dimension→token to token→dimension.','', '| Target | Workload | Original p95 ms | Reordered p95 ms | Page-major p95 ms | Reordered speedup | Page overhead vs reordered |','|---|---|---:|---:|---:|---:|---:|']
for target,rows in targets.items():
 for m in manifest:
  q={r['candidate']:r['native_kernel_only']['p95_ms'] for r in rows if r['workload_id']==m['workload_id']};lines.append(f"| {target} | {m['workload_id']} | {q['original_contiguous']:.6f} | {q['reordered_contiguous']:.6f} | {q['page_major']:.6f} | {(q['original_contiguous']/q['reordered_contiguous']-1)*100:.2f}% | {(q['page_major']/q['reordered_contiguous']-1)*100:.2f}% |")
lines+=['','Kernel-only reordered contiguous beats original contiguous and page-major on every O1–O5 workload on both targets. Append+decode selection differs on host O3/O4, where page-major is faster; Pi selects reordered contiguous throughout.','', 'No explicit SIMD, prefetch, continuous batching, GPU code, or new KV representation was added.','']
(A/'summary.md').write_text('\n'.join(lines))
